# Generated by Django 3.2.7 on 2022-02-21 15:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220221_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodgroup',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=25),
        ),
    ]
